config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'invoices#index'

  resources :invoices, only: %i[new create index show]
  resources :payments, only: %i[new create index show]
  resources :procurement_lots, only: %i[new create index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/procurement_lot.rb
class ProcurementLot < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def balance
    paid - owed
  end

  private

  def paid
    Payment
      .where(user_id: id)
      .sum(:amount)
  end

  def owed
    (Invoice.sum(:amount) / 3).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  def index
    @invoices = Invoice.all
  end

  def show
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user_id = current_user.id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:amount, :name, :description)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  def index
    @payments = Payment.all
  end

  def show
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:amount)
  end
end

app/controllers/procurement_lots_controller.rb
class ProcurementLotsController < ApplicationController
  def index
    @procurement_lots = ProcurementLot.first(100)
  end

  def new
    @procurement_lot = ProcurementLot.new
  end

  def create
    @procurement_lot = ProcurementLot.new(procurement_lot_params)

    if @procurement_lot.save
      redirect_to @procurement_lot
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @procurement_lot = ProcurementLot.find(params[:id])
  end

  private

  def procurement_lot_params
    params.require(:procurement_lot).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.name, invoice %></td>
        <td><%= invoice.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.slim
dl
  dt Amount 
  dd = @invoice.amount

  dt Name
  dd = @invoice.name

  dt Description
  dd = @invoice.description

= link_to 'Back', invoices_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title CashCounter
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .grid
      header
        => link_to 'HOME', root_path
        - if user_signed_in?
          => link_to 'log out', destroy_user_session_path, method: :delete
        = link_to 'Payments', payments_path
        =< link_to 'Procurement', procurement_lots_path
        section
          - if user_signed_in?
            p
              Your balance:
              =< current_user.balance

      p class="notice"
        = notice
      p class="alert"
        = alert

      = yield

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: 0.01 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to payment.amount, payment %></td>
        <td><%= payment.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.slim
dl
  dt Amount 
  dd = @payment.amount

= link_to 'Back', payments_path

app/views/procurement_lots/index.html.slim
h1 Procurement

table
  thead
    tr
      th Title
      th Description
  tbody
    - @procurement_lots.each do |lot| 
      tr
        td = link_to lot.title, lot  
        td = lot.description 

= link_to 'create a new lot', new_procurement_lot_path

app/views/procurement_lots/new.html.slim
= form_with(model: @procurement_lot, local: true) do |form|
  - if @procurement_lot.errors.any?
    #error_explanation
      h2
        => pluralize(@procurement_lot.errors.count, "error")
        | prohibited this procurement lot from being saved:

      ul
        - @procurement_lot.errors.full_messages.each do |message|
          li = message

  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_area :description

  .actions
    = form.submit

= link_to 'Back', procurement_lots_path

app/views/procurement_lots/show.html.slim
h1 = @procurement_lot.title
p = @procurement_lot.description
= link_to 'Back', procurement_lots_path